spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Project-Alice-89/configs.git
          clone-on-start: true
  security:
    user:
      password: 1234
server:
  port: 8888
